12_ibm_capstone_project/server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL

    path(route='about/', view=views.get_about, name='about'),

    path(route='contact/', view=views.get_contact, name='contact'),

    path(route='login/', view=views.login_request, name='login'),

    path(route='signup/', view=views.signup_request, name='signup'),

    path(route='logout/', view=views.logout_request, name='logout'),

    path(route='', view=views.get_dealerships, name='index'),

    path('dealer/<int:dealer_id>/', views.get_dealer_details, name='dealer_details'),

    path('dealer/<int:dealer_id>/review/', view=views.add_review, name='add_review')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

12_ibm_capstone_project/server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

12_ibm_capstone_project/server/djangoapp/models.py
from django.utils.timezone import now
from django.db import models
from django.utils.timezone import now


# Create your models here.

class CarMake(models.Model):
    name = models.CharField(null=False, max_length=30, default='car')
    description = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.name)

class CarModel(models.Model):
    BIKE = "Bike"
    COUPE = "Coupe"
    MINIVAN = "Mini"
    OTHER = "Other"
    PICKUP = "Pickup"
    SCOOTER = "Scooter"
    SEDAN = "Sedan"
    SPORT = "Sport"
    SUV = "SUV"
    TRUCK = "Truck"
    VAN = "Van"
    WAGON = "Wagon"

    CHOICES = [
        (BIKE, "Motor Bike"), (COUPE, "Coupe"), (MINIVAN, "Mini Van"), (PICKUP, "Pick-up Truck"), (SCOOTER, "Scooter"),
        (SEDAN, "Sedan"), (SPORT, "Sports Car"), (SUV, "SUV"), (TRUCK, "Truck"), (VAN, "Van"), (WAGON, "Wagon"), (OTHER, 'Other'),
    ]

    car_make = models.ForeignKey(CarMake, on_delete=models.CASCADE)
    dealer = models.IntegerField()
    name = models.CharField(max_length=60)
    car_type = models.CharField(max_length=15, choices=CHOICES, default=SUV)
    year = models.DateField(default=now)
    objects = models.Manager()

    def __str__(self):
        return str(self.name)

class CarDealer:
    def __init__(self, id, city, state, st, address, zip, lat, long, short_name, full_name):
        self.id = id
        self.city = city
        self.state = state
        self.st = st
        self.address = address
        self.zip = zip
        self.lat = lat
        self.long = long
        self.short_name = short_name
        self.full_name = full_name
        
    def __str__(self):
        return "Dealer name: " + self.full_name


class DealerReview:
    def __init__(self, dealership, id, name, purchase, review, car_make=None, car_model=None, car_year=None, purchase_date=None, sentiment="neutral"):
        self.dealership = dealership
        self.name = name
        self.purchase = purchase
        self.review = review
        self.purchase_date = purchase_date
        self.car_make = car_make
        self.car_model = car_model
        self.car_year = car_year
        self.sentiment = sentiment
        self.id = id

    def __str__(self):
        return self.name + "'s Review: " + self.review

12_ibm_capstone_project/server/djangoapp/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from .models import CarModel
from .restapis import get_request, get_dealers_from_cf, get_dealers_by_id, get_dealer_reviews_from_cf, post_request
from django.urls import reverse
from django.views import generic
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import date, datetime
import logging
import json

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.


# Create an `about` view to render a static about page
def get_about(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/about.html', context)


# Create a `contact` view to return a static contact page
def get_contact(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/contact.html', context)

# Create a `login_request` view to handle sign in request
def login_request(request):
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        print(user)
        if user is not None:
            login(request, user)
    next_url = request.GET.get('next')
    if next_url:
        return redirect(next_url)
    else:
        return render(request, 'djangoapp/index.html', context)

# Create a `logout_request` view to handle sign out request
def logout_request(request):
    context = {}
    logout(request)

    next_url = request.GET.get('next')
    if next_url:
        return redirect(next_url)
    else:
        return render(request, 'djangoapp/index.html', context)

# Create a `registration_request` view to handle sign up request
def signup_request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html', context)
    elif request.method == 'POST':
        # Check if user exists
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name, password=password)
            login(request, user)
            return render(request, 'djangoapp/index.html', context)
        else:
            context['message'] = "User already exists."
            return render(request, 'djangoapp/registration.html', context)

# Update the `get_dealerships` view to render the index page with a list of dealerships
def get_dealerships(request):
    context = {}
    if request.method == "GET":
        url = "https://gustavosmalv-3000.theiadocker-1-labs-prod-theiak8s-4-tor01.proxy.cognitiveclass.ai/dealerships/get"
        # Get dealers from the URL
        dealerships = get_dealers_from_cf(url)
        context["dealerships"] = dealerships
        # Concat all dealer's short name
        #dealer_names = ' '.join([dealer.short_name for dealer in dealerships])
        # Return a list of dealer short name
        #return HttpResponse(dealer_names)
    return render(request, 'djangoapp/index.html', context)

def get_dealer_details(request, dealer_id):
    context = {}
    if request.method == "GET":
        url = "https://gustavosmalv-5000.theiadocker-1-labs-prod-theiak8s-4-tor01.proxy.cognitiveclass.ai/api/get_reviews?id={0}".format(dealer_id)
        url_dealer = f"https://gustavosmalv-3000.theiadocker-1-labs-prod-theiak8s-4-tor01.proxy.cognitiveclass.ai/dealerships/get"

        reviews = get_dealer_reviews_from_cf(url, dealer_id=dealer_id)
        dealer = get_dealers_by_id(url_dealer, dealer_id=dealer_id)
        context = {
            "reviews":  reviews,
            "dealer_id": dealer_id,
            "dealer": dealer
        }
    return render(request, 'djangoapp/dealer_details.html', context)


def add_review(request, dealer_id):
    # User must be logged in before posting a review
    if request.user.is_authenticated:
        # GET request renders the page with the form for filling out a review
        if request.method == "GET":
            url = f"https://gustavosmalv-3000.theiadocker-1-labs-prod-theiak8s-4-tor01.proxy.cognitiveclass.ai/dealerships/get"
            # Get dealer details from the API
            context = {
                "cars": CarModel.objects.all().filter(dealer=dealer_id),
                "dealer": get_dealers_by_id(url, dealer_id=dealer_id),
            }
            return render(request, 'djangoapp/add_review.html', context)
        # POST request posts the content in the review submission form to the Cloudant DB using the post_review Cloud Function
        if request.method == "POST":
            form = request.POST
            review = dict()
            review["name"] = f"{request.user.first_name} {request.user.last_name}"
            review["dealership"] = dealer_id
            review["review"] = form["content"]
            review["purchase"] = form.get("purchasecheck")
            car = CarModel.objects.get(pk=form["car"])
            review["car_make"] = car.car_make.name
            review["car_model"] = car.name
            review["car_year"] = car.year.isoformat()
            
            # If the user bought the car, get the purchase date
            if form.get("purchasecheck"):
                review["purchase_date"] = datetime.strptime(form.get("purchasedate"), '%m/%d/%Y').isoformat()
            else: 
                review["purchase_date"] = None
            
            review["id"] = 10
            
            url = "https://gustavosmalv-5000.theiadocker-1-labs-prod-theiak8s-4-tor01.proxy.cognitiveclass.ai/api/post_review?id={0}".format(dealer_id)
            json_payload = review # {"review": review}  # Create a JSON payload that contains the review data
            
            # POST request with the review
            result = post_request(url, json_payload, dealer_id=dealer_id)
            if int(result.status_code) == 200:
                print("Review posted successfully.")

            # Redirect to dealer details
            return redirect("djangoapp:dealer_details", dealer_id=dealer_id)

    else:
        # If user isn't logged in, redirect to login page
        print("User must be authenticated before posting a review. Please log in.")

12_ibm_capstone_project/server/djangoapp/templates/djangoapp/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>Best Cars - About Us</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'djangoapp:index' %}">Best Cars</a>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'djangoapp:index' %}">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'djangoapp:about' %}">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                </li>
            </ul>
        </div>
        <div class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
                <a class="btn" style="color:white;" href="#">({{ user.username }})</a>
                <a class="btn btn-outline-light" href="{% url 'djangoapp:logout' %}?next={{ request.path }}">Logout</a>
            </li>
            {% else %}
            <form class="form-inline" action="{% url 'djangoapp:login' %}?next={{ request.path }}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input id="username" name="username" class="form-control mr-sm-2" type="text" placeholder="Username" required>
                    <input id="psw" name="psw" class="form-control mr-sm-2" type="password" placeholder="Password" required>
                </div>
                <button class="btn btn-outline-light mr-sm-2 my-sm-1" type="submit">Login</button>
                <a class="btn btn-outline-light" href="{% url 'djangoapp:signup' %}">Sign Up</a>
            </form>
            {% endif %}
        <div>
    </nav>

    <br>
    <h1>
        Welcome to Best Cars dealership, home to the best cars in North America. We sell domestic and imported cars at reasonable prices.
    </h1>
</body>
</html>

12_ibm_capstone_project/server/djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'djangoapp:index' %}">Best Cars</a>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'djangoapp:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'djangoapp:about' %}">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                </li>
            </ul>
        </div>
        <div class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
                <a class="btn" style="color:white;" href="#">({{ user.username }})</a>
                <a class="btn btn-outline-light" href="{% url 'djangoapp:logout' %}?next={{ request.path }}">Logout</a>
            </li>
            {% else %}
            <form class="form-inline" action="{% url 'djangoapp:login' %}?next={{ request.path }}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input id="username" name="username" class="form-control mr-sm-2" type="text" placeholder="Username" required>
                    <input id="psw" name="psw" class="form-control mr-sm-2" type="password" placeholder="Password" required>
                </div>
                <button class="btn btn-outline-light mr-sm-2 my-sm-1" type="submit">Login</button>
                <a class="btn btn-outline-light" href="{% url 'djangoapp:signup' %}">Sign Up</a>
            </form>
            {% endif %}
        <div>
    </nav>

    <div class="container">
        <h1>Review Submission</h1>
        <h4><i>for: {{dealer.full_name}}</i></h4>
        <br>
        <form action="/djangoapp/dealer/{{ dealer.id }}/review/" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="content"><b>Review:</b></label>
                <textarea class="form-control" id="content" name="content" rows="2" required></textarea>
            </div>
            <div class="form-group form-check">
                <input class="form-check-input" type="checkbox" name="purchasecheck" id="purchasecheck">
                <label for="purchasecheck">Did you purchase the car?</label>
            </div>
            <div class="form-group">
                <label for="car">Select your Car:</label>
                <select name="car" id="car" class="form-select">
                    {% for car in cars %}
                        <option selected value={{car.id}}>{{car.car_make.name}} - {{car.name}} - {{ car.year|date:"Y" }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group" data-provide="datepicker">
                <label for="purchasedate">Select your purchase date (mm/dd/yyyy):</label>
                <input class="date-own form-control" type="text" name="purchasedate" id="purchasedate">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <script type="text/javascript">
        $('.date-own').datepicker({
           format: 'mm/dd/yyyy'
         });
   </script>
</body>
</html>

12_ibm_capstone_project/server/djangoapp/templates/djangoapp/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>Best Cars - Contact Us</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
</head>

<body>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'djangoapp:index' %}">Best Cars</a>
            </div>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'djangoapp:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'djangoapp:about' %}">About Us</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                    </li>
                </ul>
            </div>
            <div class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn" style="color:white;" href="#">({{ user.username }})</a>
                    <a class="btn btn-outline-light" href="{% url 'djangoapp:logout' %}?next={{ request.path }}">Logout</a>
                </li>
                {% else %}
                <form class="form-inline" action="{% url 'djangoapp:login' %}?next={{ request.path }}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input id="username" name="username" class="form-control mr-sm-2" type="text" placeholder="Username" required>
                        <input id="psw" name="psw" class="form-control mr-sm-2" type="password" placeholder="Password" required>
                    </div>
                    <button class="btn btn-outline-light mr-sm-2 my-sm-1" type="submit">Login</button>
                    <a class="btn btn-outline-light" href="{% url 'djangoapp:signup' %}">Sign Up</a>
                </form>
                {% endif %}
            <div>
        </nav>     

    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Contact Information</h2><br>
                <p><strong>Phone:</strong> <a href="tel:+1234567890">+1 (123) 456-7890</a></p>
                <p><strong>Address:</strong> 3900 Swiss Ave #1012</p>
            </div>
        </div>
    </div>

</body>
</html>

12_ibm_capstone_project/server/djangoapp/templates/djangoapp/dealer_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'djangoapp:index' %}">Best Cars</a>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'djangoapp:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'djangoapp:about' %}">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                </li>
            </ul>
        </div>
        <div class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
                <a class="btn" style="color:white;" href="#">({{ user.username }})</a>
                <a class="btn btn-outline-light" href="{% url 'djangoapp:add_review' dealer_id%}">Add Review</a>
                <a class="btn btn-outline-light" href="{% url 'djangoapp:logout' %}?next={{ request.path }}">Logout</a>
            </li>
            {% else %}
            <form class="form-inline" action="{% url 'djangoapp:login' %}?next={{ request.path }}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input id="username" name="username" class="form-control mr-sm-2" type="text" placeholder="Username" required>
                    <input id="psw" name="psw" class="form-control mr-sm-2" type="password" placeholder="Password" required>
                </div>
                <button class="btn btn-outline-light mr-sm-2 my-sm-1" type="submit">Login</button>
                <a class="btn btn-outline-light" href="{% url 'djangoapp:signup' %}">Sign Up</a>
            </form>
            {% endif %}
        <div>
    </nav>

    <h1>Reviews for: {{ dealer.full_name }}</h1>
    <br>

    <div class="container">
        <div class="row">
            {% for review in reviews %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{{ MEDIA_URL }}/emoji/{{ review.sentiment }}.png" class="card-img-top" style="float: left; height: 40px; width: 40px; display: inline-block;">
                    <div class="card-body">
                        <h5 class="card-title">{{ review.car_make }}, {{ review.car_model }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ review.car_year }}</h6>
                        <p class="card-text">{{ review.review }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    

</body>

</html>

12_ibm_capstone_project/server/djangoapp/templates/djangoapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Best Cars - Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'djangoapp:index' %}">Best Cars</a>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'djangoapp:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'djangoapp:about' %}">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'djangoapp:contact' %}">Contact Us</a>
                </li>
            </ul>
        </div>
        <div class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li>
                <a class="btn" style="color:white;" href="#">({{ user.username }})</a>
                <a class="btn btn-outline-light" href="{% url 'djangoapp:logout' %}?next={{ request.path }}">Logout</a>
            </li>
            {% else %}
            <form class="form-inline" action="{% url 'djangoapp:login' %}?next={{ request.path }}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input id="username" name="username" class="form-control mr-sm-2" type="text" placeholder="Username" required>
                    <input id="psw" name="psw" class="form-control mr-sm-2" type="password" placeholder="Password" required>
                </div>
                <button class="btn btn-outline-light mr-sm-2 my-sm-1" type="submit">Login</button>
                <a class="btn btn-outline-light" href="{% url 'djangoapp:signup' %}">Sign Up</a>
            </form>
            {% endif %}
        <div>
    </nav>

    <table class="table" id="table" data-filter-control="true">
        <thead>
            <tr>
                <th data-field="id">ID</th>
                <th data-field="name">Name</th>
                <th data-field="city">City</th>
                <th data-field="address">Address</th>
                <th data-field="zip">Zip</th>
                <th data-field="state" data-filter-control="select">State</th>
            </tr>
        </thead>
        <tbody>
            {% for dealer in dealerships %}
                <tr>
                    <td>{{dealer.id}}</td>
                    <td><a href="{% url 'djangoapp:dealer_details' dealer.id %}">{{dealer.full_name}}</a></td>
                    <td>{{dealer.city}}</td>
                    <td>{{dealer.address}}</td>
                    <td>{{dealer.zip}}</td>
                    <td>{{dealer.st}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        $(function() {
          $('#table').bootstrapTable()
        })
    </script>
</body>
</html>